# Generated by Django 5.1.2 on 2024-11-12 17:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualInflationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('taux_inflation', models.DecimalField(decimal_places=2, help_text="Taux d'inflation annuel en pourcentage", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-100')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': "Taux d'inflation annuel",
                'verbose_name_plural': "Taux d'inflation annuels",
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Courant', 'Courant'), ('Epargne Financière', 'Ep.Financière'), ('Assurance Vie', 'Assurance Vie'), ('Epargne Entreprise', 'Epargne Entreprise')], default='Courant', max_length=64)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Action'), ('ETF', 'ETF')], max_length=5)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Titre',
                'verbose_name_plural': 'Titres',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_compte', models.CharField(max_length=64)),
                ('montant_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('€', 'Euros €')], default='€', max_length=24)),
                ('taux_rentabilite', models.FloatField()),
                ('periode', models.IntegerField()),
                ('annee_depart', models.IntegerField(default=2024)),
                ('montant_fixe_annuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nom_compte', models.CharField(max_length=100)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Achat'), ('SELL', 'Vente')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulation.stock')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RealAccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('montant_reel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_inflation', models.DecimalField(decimal_places=2, default=0, help_text="Taux d'inflation annuel en pourcentage", max_digits=4)),
                ('montant_reel_ajuste', models.DecimalField(blank=True, decimal_places=2, help_text='Montant ajusté après inflation', max_digits=10, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.simulation')),
            ],
            options={
                'verbose_name': 'Données réelles',
                'verbose_name_plural': 'Données réelles',
                'ordering': ['annee'],
                'unique_together': {('simulation', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulation.stock')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'unique_together': {('portfolio', 'stock')},
            },
        ),
    ]
